/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CompaniesCreateCompanyRequestCompanyAddressesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CompaniesCreateCompanyRequestCompany
 */
public class CompaniesCreateCompanyRequestCompanyTest {
    private final CompaniesCreateCompanyRequestCompany model = new CompaniesCreateCompanyRequestCompany();

    /**
     * Model tests for CompaniesCreateCompanyRequestCompany
     */
    @Test
    public void testCompaniesCreateCompanyRequestCompany() {
        // TODO: test CompaniesCreateCompanyRequestCompany
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tradeName'
     */
    @Test
    public void tradeNameTest() {
        // TODO: test tradeName
    }

    /**
     * Test the property 'ein'
     */
    @Test
    public void einTest() {
        // TODO: test ein
    }

    /**
     * Test the property 'states'
     */
    @Test
    public void statesTest() {
        // TODO: test states
    }

    /**
     * Test the property 'numberEmployees'
     */
    @Test
    public void numberEmployeesTest() {
        // TODO: test numberEmployees
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

}
