/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ContractorPayment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractorPaymentsApi
 */
@Disabled
public class ContractorPaymentsApiTest {

    private static ContractorPaymentsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ContractorPaymentsApi(apiClient);
    }

    /**
     * Get a single contractor payment
     *
     * Returns a single contractor payments  scope: &#x60;payrolls:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleTest() throws ApiException {
        String companyId = null;
        String contractorPaymentId = null;
        String xGustoAPIVersion = null;
        ContractorPayment response = api.getSingle(companyId, contractorPaymentId)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

    /**
     * Get contractor payments for a company
     *
     * Returns an object containing individual contractor payments, within a given time period, including totals.  scope: &#x60;payrolls:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listForCompanyTest() throws ApiException {
        String companyId = null;
        String startDate = null;
        String endDate = null;
        String contractorUuid = null;
        Boolean groupByDate = null;
        Double page = null;
        Double per = null;
        String xGustoAPIVersion = null;
        Object response = api.listForCompany(companyId, startDate, endDate)
                .contractorUuid(contractorUuid)
                .groupByDate(groupByDate)
                .page(page)
                .per(per)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

}
