/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.PayPeriod;
import com.konfigthis.client.model.PaySchedule;
import com.konfigthis.client.model.PayScheduleAssignment;
import com.konfigthis.client.model.UnprocessedTerminationPayPeriod;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaySchedulesApi
 */
@Disabled
public class PaySchedulesApiTest {

    private static PaySchedulesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PaySchedulesApi(apiClient);
    }

    /**
     * Get pay schedule assignments for a company
     *
     * This endpoint returns the current pay schedule assignment for a company, with pay schedule and employee/department mappings depending on the pay schedule type.  scope: &#x60;pay_schedules:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAssignmentsTest() throws ApiException {
        String companyId = null;
        String xGustoAPIVersion = null;
        PayScheduleAssignment response = api.getAssignments(companyId)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a pay schedule
     *
     * The pay schedule object in Gusto captures the details of when employees work and when they should be paid. A company can have multiple pay schedules.  scope: &#x60;pay_schedules:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String companyId = null;
        String payScheduleId = null;
        String xGustoAPIVersion = null;
        PaySchedule response = api.getDetails(companyId, payScheduleId)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the pay schedules for a company
     *
     * The pay schedule object in Gusto captures the details of when employees work and when they should be paid. A company can have multiple pay schedules.  scope: &#x60;pay_schedules:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String companyId = null;
        Double page = null;
        Double per = null;
        String xGustoAPIVersion = null;
        List<PaySchedule> response = api.list(companyId)
                .page(page)
                .per(per)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

    /**
     * Get termination pay periods for a company
     *
     * When a payroll admin terminates an employee and selects \&quot;Dismissal Payroll\&quot; as the employee&#39;s final payroll, their last pay period will appear on the list.  This endpoint returns the unprocessed pay periods for past and future terminated employees in a given company.  scope: &#x60;payrolls:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUnprocessedTerminationPayPeriodsTest() throws ApiException {
        String companyId = null;
        String xGustoAPIVersion = null;
        List<UnprocessedTerminationPayPeriod> response = api.listUnprocessedTerminationPayPeriods(companyId)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

    /**
     * Get pay periods for a company
     *
     * Pay periods are the foundation of payroll. Compensation, time &amp; attendance, taxes, and expense reports all rely on when they happened. To begin submitting information for a given payroll, we need to agree on the time period.  By default, this endpoint returns pay periods starting from 6 months ago to the date today.  Use the &#x60;start_date&#x60; and &#x60;end_date&#x60; parameters to change the scope of the response.  End dates can be up to 3 months in the future and there is no limit on start dates.  Starting in version &#39;2023-04-01&#39;, the eligible_employees attribute was removed from the response.  The eligible employees for a payroll are determined by the employee_compensations returned from the payrolls#prepare endpoint.  scope: &#x60;payrolls:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void list_0Test() throws ApiException {
        String companyId = null;
        String startDate = null;
        String endDate = null;
        String payrollTypes = null;
        String xGustoAPIVersion = null;
        List<PayPeriod> response = api.list_0(companyId)
                .startDate(startDate)
                .endDate(endDate)
                .payrollTypes(payrollTypes)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

}
