/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AccruingTimeOffHour;
import com.konfigthis.client.model.TimeOffPoliciesCalculateAccruingTimeOffHoursRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TimeOffPoliciesApi
 */
@Disabled
public class TimeOffPoliciesApiTest {

    private static TimeOffPoliciesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TimeOffPoliciesApi(apiClient);
    }

    /**
     * Calculate accruing time off hours
     *
     * Returns a list of accruing time off for each time off policy associated with the employee.  Factors affecting the accrued hours:   * the time off policy accrual method (whether they get pay per hour worked, per hour paid, with / without overtime, accumulate time off based on pay period / calendar year / anniversary)   * how many hours of work during this pay period   * how many hours of PTO / sick hours taken during this pay period (for per hour paid policies only)   * company pay schedule frequency (for per pay period)  If none of the parameters is passed in, the accrued time off hour will be 0.  scope: &#x60;payrolls:read&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void calculateAccruingTimeOffHoursTest() throws ApiException {
        String payrollId = null;
        String employeeId = null;
        Double regularHoursWorked = null;
        Double overtimeHoursWorked = null;
        Double doubleOvertimeHoursWorked = null;
        Double ptoHoursUsed = null;
        Double sickHoursUsed = null;
        String xGustoAPIVersion = null;
        List<AccruingTimeOffHour> response = api.calculateAccruingTimeOffHours(payrollId, employeeId)
                .regularHoursWorked(regularHoursWorked)
                .overtimeHoursWorked(overtimeHoursWorked)
                .doubleOvertimeHoursWorked(doubleOvertimeHoursWorked)
                .ptoHoursUsed(ptoHoursUsed)
                .sickHoursUsed(sickHoursUsed)
                .xGustoAPIVersion(xGustoAPIVersion)
                .execute();
        // TODO: test validations
    }

}
